---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero
  client_rb:
    environment: dev
  attributes:
    mysql-multi:
      master_ip: '192.168.0.21'
      slave_ip: ['192.168.0.22']
      server_repl_password: 'VeryBadReplPasswd'

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[mysql-multi::default]

  - name: master
    run_list:
      - recipe[mysql-multi::mysql_master]

  - name: slave
    run_list:
      - recipe[mysql-multi::mysql_slave]
