---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[mysql-multi::default]
    attributes:
      mysql:
        server_root_password: ilikerandompasswords

  - name: master
    run_list:
      - recipe[mysql-multi::mysql_master]
    attributes:
      mysql:
        server_root_password: ilikerandompasswords

  - name: slave
    run_list:
      - recipe[mysql-multi::mysql_slave]
    attributes:
      mysql:
        server_root_password: ilikerandompasswords
